mlflow:
  tracking_uri: "./mlruns"
  experiment_name: "bank_marketing_experiment"

data:
  raw_train_path: "./data/raw/train.csv"
  raw_test_path: "./data/raw/test.csv"
  processed_train_path: "./data/processed/train.csv"
  processed_test_path: "./data/processed/test.csv"
  preprocessed_train_path: "./data/preprocessed/train.csv"
  preprocessed_test_path: "./data/preprocessed/test.csv"
  engineered_train_path: "./data/engineered/train.csv"
  engineered_test_path: "./data/engineered/test.csv"

training:
  model_type: "xgboost"
  use_tuning: true
  search_method: "grid"  # "grid" or "bayesian"
  param_grid:            # Used only if use_tuning is true
    max_depth: [6, 10, 15]
    learning_rate: [0.01, 0.1, 0.2]
    n_estimators: [50, 100, 150]
    colsample_bytree: [0.8, 1.0]
  direct_hyperparameters: # Used if use_tuning is false
    max_depth: 10
    learning_rate: 0.1
    n_estimators: 150
    colsample_bytree: 0.8

model_registry:
  current_model_roc_auc: 0.80
